name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image and run tests with Docker
        run: |
          docker compose version
          docker compose build --pull computer-use-demo
          docker compose run --rm --no-deps --entrypoint python computer-use-demo -m pytest -q


