name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare .env for Compose
        run: |
          if [ -f env_template.txt ]; then
            cp env_template.txt .env
          else
            printf "%s\n" \
              "POSTGRES_DB=chat_sessions" \
              "POSTGRES_USER=computeruse" \
              "POSTGRES_PASSWORD=computeruse123" \
              "POSTGRES_PORT=5432" \
              "ANTHROPIC_API_KEY=dummy" > .env
          fi

      - name: Build image and run tests with Docker
        run: |
          docker compose version
          docker compose build --pull computer-use-demo
          # Run with an in-container SQLite URL to avoid Postgres dependency in CI
          docker compose run --rm --no-deps -e DATABASE_URL=sqlite+pysqlite:///:memory: \
            --entrypoint python computer-use-demo -m pytest -q


